version: "3.8"
services:
  frontend:
    build:
      context: GPTutor-Frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - '10888:10888'
    networks:
      - app

  backend:
    build: ./GPTutor-Backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    env_file: .env
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url": "jdbc:postgresql://postgresql:5432/postgres",
            "spring.datasource.username": "${POSTGRES_USER}",
            "spring.datasource.password": "${POSTGRES_PASSWORD}",
            "auth.client.secret": "${AUTH_SECRET_KEY}",
            "auth.skip": "${SKIP_AUTH}",
            "vk.key": "${VK_KEY}",
            "cors.allowed.origins": "${CORS_ORIGIN}"
     }'
    networks:
      - app

  postgresql:
    image: 'postgres:13.1-alpine'
    container_name: postgresql
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app


volumes:
  db-data:

networks:
  app:
    driver: bridge