version: '3.9'

services:
  frontend:
    build:
      context: GPTutor-Frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - www-html:/app/build/
    networks:
      - app

  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - frontend
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - www-html:/var/www/html
      - ./nginx-conf-local.d:/etc/nginx/conf.d
    networks:
      - app

  backend:
    build: ./GPTutor-Backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    env_file: .env
    networks:
      - app

  postgresql:
    image: 'postgres:13.1-alpine'
    container_name: postgresql
    env_file: .env
    networks:
      - app

volumes:
  www-html:

networks:
  app:
    driver: bridge
