version: "3.8"
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/nginx/conf
      - ./certbot/www:/usr/share/nginx/html
    networks:
      - frontend-network
      - backend-network

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --agree-tos --no-eff-email --force-renewal -d gptutor.space
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/usr/share/nginx/html
    depends_on:
      - nginx
    networks:
      - frontend-network

  backend:
    build: ./GPTutor-Backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  frontend:
    build: ./GPTutor-Frontend
    restart: always
    networks:
      - frontend-network

  postgresql:
    image: 'postgres:13.1-alpine'
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123

networks:
  frontend-network:
  backend-network: