version: "3.8"
services:
  frontend:
    build: ./GPTutor-Frontend
    container_name: frontend
    volumes:
      - www-html:/app/build/
    networks:
      - app

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - www-html:/var/www/html
      - ./nginx-conf.d:/etc/nginx/nginx-conf.d
      - etc-letsencrypt:/etc/letsencrypt
    networks:
      - app

  certbot:
    container_name: certbot
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --register-unsafely-without-email --agree-tos --no-eff-email -d gptutor.space

  backend:
    build: ./GPTutor-Backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - app

  postgresql:
    image: 'postgres:13.1-alpine'
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    networks:
      - app

volumes:
  www-html:
  etc-letsencrypt:

networks:
  app:
    driver: bridge
